name: Build

on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:

    - name: Git repository checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox virtualenv

    - name: Run tests
      run: |
        make test
